var player;
var platforms;
var cursors;
var enemies;
// var enemiesMax;
var coins;
var coin;
var score = 0;
var scoreText;
var nightsky;
var gameTimer = 10;
var enemiesMax = 10;
var enemy;
var timer;
var endTimer;
var minSpeed = 50;
var maxSpeed = 100;
var lose;
var emitter;